int(input())
a = set(map(int, input().split()))
int(input())
b = set(map(int, input().split()))
d1 = a.difference(b)
d2 = b.difference(a)
d1.update(d2)
dif = list(d1)
dif.sort()
for u in dif: print(u)
